# Site
name: "GELinC"
title: "GELinC"
description: "Grupo de Estudos em Linguística Computacional"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 'https://gelinc.github.io/'
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'gelinc'
mailchimp-list: 'https://mailchi.mp/d8af755174cf/newsletter'
include: ["_pages"]
permalink: /:title/
email: 'gelincunb@gmail.com'
# Instagram nick for use in Instagram cards and follow button.
instagram: '' # if no instagram in this config, the instagram follow button will be removed

# Authors
authors:
  Juliana:
    name: Juliana
    display_name: Juliana Porto
    avatar: 'assets/images/avatar-juliana.png'
    email: julianaporto169@gmail.com
    lattes: http://lattes.cnpq.br/6272654670954803
    linkedin: https://www.linkedin.com/in/juliana-porto-7070a6198/
    description: "Estudante de Letras Português da Universidade de Brasília. Pesquisa e atua profissionalmente na área de Linguística Computacional, ou processamento de linguagem natural, na Alana AI. É entusiasta a respeito dos conhecimentos de Linguística de Corpus e áreas relacionadas à inteligência artificial."
  Pedro:
    name: Pedro
    display_name: Pedro Henrique B. Silvério    
    avatar: 'assets/images/avatar-pedro.png'
    email: psilverio27@gmail.com
    lattes: http://lattes.cnpq.br/4195490906909746
    linkedin: https://www.linkedin.com/in/pedrohenriquebarrossilverio
    description: "Estudante de Línguas Estrangeiras Aplicadas ao Multilinguismo e à Sociedade da Informação da Universidade de Brasília. Pesquisador na área de Linguística Computacional, ou processamento de linguagem natural. Desenvolvedor do Blog e entusiasta em áreas relacionadas à Tecnologia, Multilinguismo no Ciberespaço e Linguistíca Computacional."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
