# Site
name: "GELinC-UnB"
title: "GELinC-UnB"
description: "Grupo de Estudos em Linguística Computacional | Blog do grupo de estudos de linguística computacional da UnB (Universidade de Brasília)"
logo: 'assets/images/GELinC_simples.png'
favicon: 'assets/images/GELinC_simples.png'
baseurl: ''
google_analytics: 'G-SQ4ED0JHVM'
disqus: 'gelinc'
mailchimp-list: 'https://gmail.us5.list-manage.com/subscribe/post?u=2219e9e3f830fe06a3572e5ab&amp;id=84a8514219'
include: ["_pages"]
permalink: /:title/
email:
instagram: gelinc_unb

# Authors
authors:
  Thiago:
    name: Thiago
    display_name: Thiago Blanch Pires
    avatar: 'assets/images/avatar-thiago.png'
    email:
    lattes: http://lattes.cnpq.br/9911777987987166
    linkedin:
    description: "Professor adjunto do curso bacharelado em Línguas Estrangeiras Aplicadas ao Multilinguismo e à Sociedade da Informação (LEA-MSI) no Departamento de Línguas Estrangeiras e Tradução (LET), vinculado ao Instituto de Letras (IL) da Universidade de Brasília (UnB). Foi coordenador do curso de graduação (LEA-MSI) de março de 2018 a março de 2020. Atua no ensino da língua inglesa, dos estudos de corpora, e do tratamento automatizado das línguas naturais. Doutor em Gestão da Informação pelo Programa de Pós-Graduação em Ciência da Informação (PPGCinf) da Universidade de Brasília, com período de bolsa sanduíche na Universität Bremen, Alemanha, sob supervisão do prof. dr. John Bateman. Possui interesse de estudo nas áreas de Organização da Informação e do Conhecimento, Linguística Computacional, e Multimodalidade. Possui graduação e mestrado em Letras - Língua Inglesa e Literaturas pela Universidade Federal de Santa Catarina, sendo o mestrado realizado no Programa de Pós-Graduação em Inglês (PPGI), tendo como foco a Análise Textual na interface dos campos dos Estudos de Tradução baseados em Corpus e da Linguística Sistêmico-Funcional."
  Isabel:
    name: Isabel
    display_name: Isabel Agnes Zafred
    avatar: 'assets/images/avatar-isabel.png'
    email: isaazafred@gmail.com
    lattes: http://lattes.cnpq.br/4693048006244501
    linkedin:
    description: "Estudante de Línguas Estrangeiras Aplicadas da Universidade de Brasília. Aficionada por programação desde o Ensino Médio, pesquisa na área de Linguística Computacional pelo grupo GELinC."
  Juliana:
    name: Juliana
    display_name: Juliana Porto
    avatar: 'assets/images/avatar-juliana.png'
    email: julianaporto169@gmail.com
    lattes: http://lattes.cnpq.br/6272654670954803
    linkedin: https://www.linkedin.com/in/juliana-porto-7070a6198
    description: "Estudante de Letras Português da Universidade de Brasília. Pesquisa e atua profissionalmente na área de Linguística Computacional, ou processamento de linguagem natural, na Alana AI. É entusiasta a respeito dos conhecimentos de Linguística de Corpus e áreas relacionadas à inteligência artificial."
  Pedro:
    name: Pedro
    display_name: Pedro Henrique B. Silvério    
    avatar: 'assets/images/avatar-pedro.png'
    email: psilverio27@gmail.com
    lattes: http://lattes.cnpq.br/4195490906909746
    linkedin: https://www.linkedin.com/in/pedrohenriquebarrossilverio
    description: "Estudante de Línguas Estrangeiras Aplicadas ao Multilinguismo e à Sociedade da Informação da Universidade de Brasília. Pesquisador na área de Linguística Computacional, ou processamento de linguagem natural. Desenvolvedor do Blog e entusiasta em áreas relacionadas à Tecnologia, Multilinguismo no Ciberespaço e Linguistíca Computacional."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
